create table spatial_source_registry (
    id bigint generated by default as identity,
    source_name varchar(200) not null,
    source_type varchar(60) not null,
    phase integer not null,
    provider varchar(120),
    source_url varchar(500),
    jurisdiction_code varchar(80) default 'ASAN',
    license_note text,
    data_standard varchar(120),
    collected_at timestamp,
    data_effective_on date,
    content_hash varchar(128),
    status varchar(40) not null default 'READY',
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_spatial_source_registry primary key (id),
    constraint uk_spatial_source_registry_name unique (source_name)
);

create table spatial_admin_boundaries (
    id bigint generated by default as identity,
    source_id bigint not null,
    boundary_type varchar(40) not null,
    boundary_code varchar(80),
    boundary_name varchar(200) not null,
    parent_code varchar(80),
    valid_from date,
    valid_to date,
    centroid_lat decimal(12,8),
    centroid_lon decimal(12,8),
    min_lat decimal(12,8),
    max_lat decimal(12,8),
    min_lon decimal(12,8),
    max_lon decimal(12,8),
    geometry_format varchar(20),
    geometry_payload text,
    geometry_quality varchar(40) not null default 'SOURCE_PROVIDED',
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_spatial_admin_boundaries primary key (id),
    constraint fk_spatial_admin_boundaries_source foreign key (source_id) references spatial_source_registry (id),
    constraint uk_spatial_admin_boundaries unique (source_id, boundary_type, boundary_code, boundary_name)
);

create table spatial_address_points (
    id bigint generated by default as identity,
    source_id bigint not null,
    road_address text,
    jibun_address text,
    building_name varchar(300),
    building_id varchar(120),
    road_name varchar(200),
    admin_code varchar(80),
    legal_dong_code varchar(80),
    admin_name varchar(120),
    legal_dong_name varchar(120),
    latitude decimal(12,8),
    longitude decimal(12,8),
    geometry_quality varchar(40) not null default 'SOURCE_PROVIDED',
    raw_metadata text,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_spatial_address_points primary key (id),
    constraint fk_spatial_address_points_source foreign key (source_id) references spatial_source_registry (id)
);

create table spatial_road_segments (
    id bigint generated by default as identity,
    source_id bigint not null,
    road_name varchar(200),
    road_code varchar(120),
    road_type varchar(80),
    manager varchar(120),
    detail_location text,
    centroid_lat decimal(12,8),
    centroid_lon decimal(12,8),
    min_lat decimal(12,8),
    max_lat decimal(12,8),
    min_lon decimal(12,8),
    max_lon decimal(12,8),
    geometry_format varchar(20),
    geometry_payload text,
    geometry_quality varchar(40) not null default 'SOURCE_PROVIDED',
    raw_metadata text,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_spatial_road_segments primary key (id),
    constraint fk_spatial_road_segments_source foreign key (source_id) references spatial_source_registry (id)
);

create table spatial_facilities (
    id bigint generated by default as identity,
    source_id bigint not null,
    facility_type varchar(60) not null,
    facility_name varchar(300),
    external_id varchar(120),
    address text,
    admin_name varchar(120),
    manager varchar(120),
    phone varchar(80),
    operation_status varchar(80),
    latitude decimal(12,8),
    longitude decimal(12,8),
    centroid_lat decimal(12,8),
    centroid_lon decimal(12,8),
    min_lat decimal(12,8),
    max_lat decimal(12,8),
    min_lon decimal(12,8),
    max_lon decimal(12,8),
    geometry_format varchar(20),
    geometry_payload text,
    geometry_quality varchar(40) not null default 'SOURCE_PROVIDED',
    raw_metadata text,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_spatial_facilities primary key (id),
    constraint fk_spatial_facilities_source foreign key (source_id) references spatial_source_registry (id)
);

create table spatial_parking_restrictions (
    id bigint generated by default as identity,
    source_id bigint not null,
    restriction_id varchar(120),
    road_name varchar(200),
    detail_location text,
    restriction_type varchar(80),
    weekday_time varchar(120),
    saturday_time varchar(120),
    holiday_time varchar(120),
    effective_from date,
    effective_to date,
    manager varchar(120),
    phone varchar(80),
    latitude decimal(12,8),
    longitude decimal(12,8),
    geometry_format varchar(20),
    geometry_payload text,
    geometry_quality varchar(40) not null default 'SOURCE_PROVIDED',
    raw_metadata text,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_spatial_parking_restrictions primary key (id),
    constraint fk_spatial_parking_restrictions_source foreign key (source_id) references spatial_source_registry (id)
);

create table spatial_location_resolution_runs (
    id uuid not null,
    complaint_id uuid,
    complaint_issue_id uuid,
    input_text text not null,
    normalized_location_text text,
    status varchar(40) not null,
    blocker varchar(40),
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_spatial_location_resolution_runs primary key (id),
    constraint fk_spatial_location_runs_complaint foreign key (complaint_id) references complaints (id),
    constraint fk_spatial_location_runs_issue foreign key (complaint_issue_id) references complaint_issues (id)
);

create table spatial_location_candidates (
    id uuid not null,
    run_id uuid not null,
    candidate_type varchar(60) not null,
    label varchar(300) not null,
    address text,
    source_layer varchar(80) not null,
    source_record_id varchar(120),
    admin_boundary_id bigint,
    confidence varchar(20) not null,
    confidence_score decimal(5,4) not null,
    needs_human_confirmation boolean not null default true,
    latitude decimal(12,8),
    longitude decimal(12,8),
    evidence_summary text,
    created_at timestamp not null,
    constraint pk_spatial_location_candidates primary key (id),
    constraint fk_spatial_location_candidates_run foreign key (run_id) references spatial_location_resolution_runs (id),
    constraint fk_spatial_location_candidates_boundary foreign key (admin_boundary_id) references spatial_admin_boundaries (id)
);

create index idx_spatial_source_registry_type_status on spatial_source_registry (source_type, status, phase);
create index idx_spatial_admin_boundaries_name on spatial_admin_boundaries (boundary_name, boundary_type);
create index idx_spatial_admin_boundaries_bbox on spatial_admin_boundaries (min_lat, max_lat, min_lon, max_lon);
create index idx_spatial_address_points_admin on spatial_address_points (admin_name, legal_dong_name);
create index idx_spatial_address_points_lat_lon on spatial_address_points (latitude, longitude);
create index idx_spatial_road_segments_name on spatial_road_segments (road_name);
create index idx_spatial_facilities_type_name on spatial_facilities (facility_type, facility_name);
create index idx_spatial_facilities_admin on spatial_facilities (admin_name);
create index idx_spatial_facilities_lat_lon on spatial_facilities (latitude, longitude);
create index idx_spatial_parking_road on spatial_parking_restrictions (road_name, restriction_type);
create index idx_spatial_location_runs_complaint on spatial_location_resolution_runs (complaint_id, complaint_issue_id, created_at);
create index idx_spatial_location_candidates_run on spatial_location_candidates (run_id, confidence_score);
