create table complaints (
    id uuid not null,
    source_channel varchar(50) not null,
    raw_text text not null,
    location_text varchar(500),
    status varchar(30) not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_complaints primary key (id)
);

create table departments (
    id bigint generated by default as identity,
    code varchar(50) not null,
    name varchar(100) not null,
    description text,
    active boolean not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_departments primary key (id),
    constraint uk_departments_code unique (code)
);

create table knowledge_documents (
    id bigint generated by default as identity,
    document_type varchar(30) not null,
    title varchar(200) not null,
    source_name varchar(200) not null,
    source_url varchar(500),
    content text not null,
    keywords varchar(500) not null,
    legal_basis varchar(500),
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_knowledge_documents primary key (id)
);

create table complaint_attachments (
    id uuid not null,
    complaint_id uuid not null,
    original_filename varchar(255) not null,
    content_type varchar(100),
    size bigint not null,
    storage_key varchar(500) not null,
    created_at timestamp not null,
    constraint pk_complaint_attachments primary key (id),
    constraint fk_complaint_attachments_complaint foreign key (complaint_id) references complaints (id)
);

create table complaint_analysis (
    id bigint generated by default as identity,
    complaint_id uuid not null,
    intent varchar(100) not null,
    urgency varchar(30) not null,
    sentiment varchar(30) not null,
    department_id bigint not null,
    location_text varchar(500),
    geo_json text,
    analysis_json text not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_complaint_analysis primary key (id),
    constraint uk_complaint_analysis_complaint unique (complaint_id),
    constraint fk_complaint_analysis_complaint foreign key (complaint_id) references complaints (id),
    constraint fk_complaint_analysis_department foreign key (department_id) references departments (id)
);

create table official_drafts (
    id bigint generated by default as identity,
    complaint_id uuid not null,
    draft_text text not null,
    model_name varchar(100) not null,
    status varchar(30) not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_official_drafts primary key (id),
    constraint fk_official_drafts_complaint foreign key (complaint_id) references complaints (id)
);

create table draft_revisions (
    id bigint generated by default as identity,
    official_draft_id bigint not null,
    before_text text not null,
    after_text text not null,
    revised_by varchar(100) not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_draft_revisions primary key (id),
    constraint fk_draft_revisions_official_draft foreign key (official_draft_id) references official_drafts (id)
);

create table rag_contexts (
    id bigint generated by default as identity,
    complaint_id uuid not null,
    official_draft_id bigint,
    knowledge_document_id bigint not null,
    legal_basis varchar(500),
    content_snippet text not null,
    score float(53) not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_rag_contexts primary key (id),
    constraint fk_rag_contexts_complaint foreign key (complaint_id) references complaints (id),
    constraint fk_rag_contexts_official_draft foreign key (official_draft_id) references official_drafts (id),
    constraint fk_rag_contexts_knowledge_document foreign key (knowledge_document_id) references knowledge_documents (id)
);

create index idx_complaints_status_created_at on complaints (status, created_at);
create index idx_complaint_attachments_complaint_id on complaint_attachments (complaint_id);
create index idx_official_drafts_complaint_id_created_at on official_drafts (complaint_id, created_at);
create index idx_rag_contexts_complaint_id_score on rag_contexts (complaint_id, score);
create index idx_rag_contexts_official_draft_id_score on rag_contexts (official_draft_id, score);
