create table audit_logs (
    id bigint generated by default as identity,
    method varchar(20) not null,
    path varchar(500) not null,
    actor varchar(100),
    client_ip varchar(100),
    status_code integer not null,
    duration_ms bigint not null,
    created_at timestamp not null,
    constraint pk_audit_logs primary key (id)
);

create index idx_audit_logs_created_at on audit_logs (created_at);
create index idx_audit_logs_path_created_at on audit_logs (path, created_at);
