create table api_users (
    id bigint generated by default as identity,
    username varchar(100) not null,
    api_key_hash varchar(128) not null,
    role varchar(30) not null,
    active boolean not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_api_users primary key (id),
    constraint uk_api_users_username unique (username),
    constraint uk_api_users_api_key_hash unique (api_key_hash)
);

create index idx_api_users_api_key_hash_active on api_users (api_key_hash, active);
