alter table complaints add column receipt_number varchar(60);
alter table complaints add column title varchar(200);

update complaints
set receipt_number = concat('LEGACY-', id)
where receipt_number is null;

alter table complaints alter column receipt_number set not null;
alter table complaints add constraint uk_complaints_receipt_number unique (receipt_number);
create index idx_complaints_receipt_number on complaints (receipt_number);

alter table complaint_analysis add column complaint_type varchar(50);

update complaint_analysis
set complaint_type = 'GENERAL'
where complaint_type is null;

alter table complaint_analysis alter column complaint_type set not null;
create index idx_complaint_analysis_type_urgency on complaint_analysis (complaint_type, urgency);

create table knowledge_document_chunks (
    id bigint generated by default as identity,
    knowledge_document_id bigint not null,
    chunk_index integer not null,
    content text not null,
    keywords varchar(500) not null,
    legal_basis varchar(500),
    embedding_id varchar(200),
    token_count integer,
    active boolean not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_knowledge_document_chunks primary key (id),
    constraint fk_knowledge_document_chunks_document foreign key (knowledge_document_id) references knowledge_documents (id),
    constraint uk_knowledge_document_chunks_document_index unique (knowledge_document_id, chunk_index)
);

create index idx_knowledge_document_chunks_document_id on knowledge_document_chunks (knowledge_document_id);
create index idx_knowledge_document_chunks_active on knowledge_document_chunks (active);

alter table rag_contexts add column knowledge_document_chunk_id bigint;
alter table rag_contexts add constraint fk_rag_contexts_knowledge_document_chunk foreign key (knowledge_document_chunk_id) references knowledge_document_chunks (id);
create index idx_rag_contexts_knowledge_document_chunk_id on rag_contexts (knowledge_document_chunk_id);
