alter table complaints add column redacted_text text;
alter table complaints add column workflow_blocker varchar(40);
alter table complaints add column version bigint not null default 0;

alter table complaints drop constraint if exists complaints_status_check;

update complaints
set redacted_text = raw_text
where redacted_text is null;

alter table complaints alter column redacted_text set not null;

update complaints set status = 'TRIAGE_REVIEW' where status in ('ANALYZED', 'IN_PROGRESS');
update complaints set status = 'DRAFT_REVIEW' where status = 'DRAFT_GENERATED';

alter table official_drafts add column reviewed_by varchar(100);
alter table official_drafts add column approved_by varchar(100);
alter table official_drafts add column review_notes text;
alter table official_drafts add column version bigint not null default 0;

alter table official_drafts drop constraint if exists official_drafts_status_check;

update official_drafts set status = 'REJECTED' where status in ('DRAFT', 'REVISED');

alter table knowledge_documents add column purpose varchar(40) not null default 'UNVERIFIED_LEGACY';
alter table knowledge_documents add column verification_status varchar(40) not null default 'UNVERIFIED_LEGACY';
alter table knowledge_documents add column jurisdiction_code varchar(80);
alter table knowledge_documents add column effective_from date;
alter table knowledge_documents add column effective_to date;
alter table knowledge_documents add column content_hash varchar(128);

create table source_registry (
    id bigint generated by default as identity,
    name varchar(200) not null,
    source_type varchar(40) not null,
    base_url varchar(500),
    jurisdiction_code varchar(80),
    status varchar(30) not null,
    last_verified_at timestamp,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_source_registry primary key (id),
    constraint uk_source_registry_name unique (name)
);

create table legal_document_versions (
    id bigint generated by default as identity,
    source_registry_id bigint not null,
    external_id varchar(200) not null,
    title varchar(500) not null,
    jurisdiction_code varchar(80),
    promulgated_at date,
    effective_from date not null,
    effective_to date,
    status varchar(30) not null,
    content_hash varchar(128) not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_legal_document_versions primary key (id),
    constraint fk_legal_document_versions_source foreign key (source_registry_id) references source_registry (id),
    constraint uk_legal_document_versions_source_hash unique (source_registry_id, external_id, content_hash)
);

create table legal_provisions (
    id bigint generated by default as identity,
    legal_document_version_id bigint not null,
    provision_key varchar(200) not null,
    heading varchar(500),
    content text not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_legal_provisions primary key (id),
    constraint fk_legal_provisions_version foreign key (legal_document_version_id) references legal_document_versions (id),
    constraint uk_legal_provisions_version_key unique (legal_document_version_id, provision_key)
);

create table legal_relations (
    id bigint generated by default as identity,
    source_provision_id bigint not null,
    target_provision_id bigint not null,
    relation_type varchar(40) not null,
    created_at timestamp not null,
    constraint pk_legal_relations primary key (id),
    constraint fk_legal_relations_source foreign key (source_provision_id) references legal_provisions (id),
    constraint fk_legal_relations_target foreign key (target_provision_id) references legal_provisions (id)
);

create table knowledge_purpose (
    id bigint generated by default as identity,
    knowledge_document_id bigint not null,
    purpose varchar(40) not null,
    legal_evidence_allowed boolean not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_knowledge_purpose primary key (id),
    constraint fk_knowledge_purpose_document foreign key (knowledge_document_id) references knowledge_documents (id),
    constraint uk_knowledge_purpose_document_purpose unique (knowledge_document_id, purpose)
);

create table organization_units (
    id bigint generated by default as identity,
    code varchar(80) not null,
    name varchar(200) not null,
    jurisdiction_code varchar(80) not null,
    synthetic_demo boolean not null,
    active boolean not null,
    valid_from date,
    valid_to date,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_organization_units primary key (id),
    constraint uk_organization_units_code unique (code)
);

create table assignment_rules (
    id bigint generated by default as identity,
    organization_unit_id bigint not null,
    complaint_type varchar(50) not null,
    jurisdiction_code varchar(80) not null,
    rule_text text not null,
    priority integer not null,
    synthetic_demo boolean not null,
    active boolean not null,
    valid_from date,
    valid_to date,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_assignment_rules primary key (id),
    constraint fk_assignment_rules_unit foreign key (organization_unit_id) references organization_units (id)
);

create table historical_complaints (
    id uuid not null,
    external_id varchar(200),
    redacted_text text not null,
    department_code varchar(80),
    approved_for_auxiliary_use boolean not null,
    content_hash varchar(128) not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_historical_complaints primary key (id),
    constraint uk_historical_complaints_hash unique (content_hash)
);

create table complaint_issues (
    id uuid not null,
    complaint_id uuid not null,
    issue_index integer not null,
    summary varchar(500) not null,
    complaint_type varchar(50) not null,
    jurisdiction_status varchar(40) not null,
    safety_risk varchar(40) not null,
    expression_risk varchar(40) not null,
    processability varchar(40) not null,
    status varchar(40) not null,
    version bigint not null default 0,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_complaint_issues primary key (id),
    constraint fk_complaint_issues_complaint foreign key (complaint_id) references complaints (id),
    constraint uk_complaint_issues_complaint_index unique (complaint_id, issue_index)
);

create table department_tasks (
    id uuid not null,
    complaint_issue_id uuid not null,
    department_code varchar(80) not null,
    recommendation_reason text not null,
    status varchar(40) not null,
    confirmed_by varchar(100),
    version bigint not null default 0,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_department_tasks primary key (id),
    constraint fk_department_tasks_issue foreign key (complaint_issue_id) references complaint_issues (id)
);

create table location_candidates (
    id uuid not null,
    complaint_issue_id uuid not null,
    location_text varchar(500) not null,
    source varchar(40) not null,
    status varchar(40) not null,
    confirmed_by varchar(100),
    confirmed_at timestamp,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_location_candidates primary key (id),
    constraint fk_location_candidates_issue foreign key (complaint_issue_id) references complaint_issues (id)
);

create table idempotency_records (
    id uuid not null,
    operation varchar(100) not null,
    idempotency_key varchar(200) not null,
    resource_id varchar(200) not null,
    created_at timestamp not null,
    constraint pk_idempotency_records primary key (id),
    constraint uk_idempotency_records_operation_key unique (operation, idempotency_key)
);

create table processing_jobs (
    id uuid not null,
    complaint_id uuid not null,
    job_type varchar(40) not null,
    status varchar(40) not null,
    idempotency_key varchar(200) not null,
    attempts integer not null,
    max_attempts integer not null,
    lease_until timestamp,
    failure_reason text,
    result_reference varchar(200),
    cost_units bigint not null,
    version bigint not null default 0,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_processing_jobs primary key (id),
    constraint fk_processing_jobs_complaint foreign key (complaint_id) references complaints (id),
    constraint uk_processing_jobs_type_key unique (job_type, idempotency_key)
);

create table retrieval_runs (
    id uuid not null,
    complaint_id uuid not null,
    processing_job_id uuid,
    query_text text not null,
    purpose varchar(40) not null,
    status varchar(40) not null,
    filters_json text not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_retrieval_runs primary key (id),
    constraint fk_retrieval_runs_complaint foreign key (complaint_id) references complaints (id),
    constraint fk_retrieval_runs_job foreign key (processing_job_id) references processing_jobs (id)
);

create table evidence_snapshots (
    id uuid not null,
    complaint_id uuid not null,
    retrieval_run_id uuid,
    source_type varchar(40) not null,
    source_id varchar(200) not null,
    title varchar(500) not null,
    content text not null,
    source_url varchar(500),
    jurisdiction_code varchar(80),
    effective_from date,
    effective_to date,
    source_status varchar(40) not null,
    content_hash varchar(128) not null,
    supports_claim boolean not null,
    created_at timestamp not null,
    constraint pk_evidence_snapshots primary key (id),
    constraint fk_evidence_snapshots_complaint foreign key (complaint_id) references complaints (id),
    constraint fk_evidence_snapshots_run foreign key (retrieval_run_id) references retrieval_runs (id)
);

create table ai_runs (
    id uuid not null,
    complaint_id uuid not null,
    processing_job_id uuid,
    task_type varchar(40) not null,
    provider varchar(80) not null,
    model_name varchar(100) not null,
    prompt_version varchar(80) not null,
    schema_version varchar(80) not null,
    input_hash varchar(128) not null,
    output_hash varchar(128),
    status varchar(40) not null,
    cost_units bigint not null,
    duration_ms bigint not null,
    retry_count integer not null,
    failure_reason text,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_ai_runs primary key (id),
    constraint fk_ai_runs_complaint foreign key (complaint_id) references complaints (id),
    constraint fk_ai_runs_job foreign key (processing_job_id) references processing_jobs (id)
);

create table draft_claims (
    id uuid not null,
    official_draft_id bigint not null,
    claim_index integer not null,
    claim_text text not null,
    claim_type varchar(40) not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_draft_claims primary key (id),
    constraint fk_draft_claims_draft foreign key (official_draft_id) references official_drafts (id),
    constraint uk_draft_claims_draft_index unique (official_draft_id, claim_index)
);

create table claim_evidence_links (
    draft_claim_id uuid not null,
    evidence_snapshot_id uuid not null,
    relation_type varchar(40) not null,
    created_at timestamp not null,
    constraint pk_claim_evidence_links primary key (draft_claim_id, evidence_snapshot_id),
    constraint fk_claim_evidence_links_claim foreign key (draft_claim_id) references draft_claims (id),
    constraint fk_claim_evidence_links_evidence foreign key (evidence_snapshot_id) references evidence_snapshots (id)
);

create table verification_results (
    id uuid not null,
    complaint_id uuid not null,
    official_draft_id bigint,
    rule_code varchar(80) not null,
    status varchar(40) not null,
    message text not null,
    hard_failure boolean not null,
    created_at timestamp not null,
    constraint pk_verification_results primary key (id),
    constraint fk_verification_results_complaint foreign key (complaint_id) references complaints (id),
    constraint fk_verification_results_draft foreign key (official_draft_id) references official_drafts (id)
);

create table human_reviews (
    id uuid not null,
    complaint_id uuid not null,
    official_draft_id bigint,
    action varchar(40) not null,
    actor varchar(100) not null,
    actor_role varchar(40) not null,
    notes text,
    idempotency_key varchar(200) not null,
    created_at timestamp not null,
    constraint pk_human_reviews primary key (id),
    constraint fk_human_reviews_complaint foreign key (complaint_id) references complaints (id),
    constraint fk_human_reviews_draft foreign key (official_draft_id) references official_drafts (id),
    constraint uk_human_reviews_idempotency_key unique (idempotency_key)
);

create table complaint_sensitive_payloads (
    id uuid not null,
    complaint_id uuid not null,
    raw_storage_reference varchar(500) not null,
    redacted_text text not null,
    pii_findings text not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_complaint_sensitive_payloads primary key (id),
    constraint fk_complaint_sensitive_payloads_complaint foreign key (complaint_id) references complaints (id),
    constraint uk_complaint_sensitive_payloads_complaint unique (complaint_id)
);

create table attachment_analysis (
    id uuid not null,
    attachment_id uuid not null,
    quarantine_status varchar(40) not null,
    detected_type varchar(100),
    malware_status varchar(40) not null,
    exif_removed boolean not null,
    ocr_text text,
    pii_findings text not null,
    approved_for_ai boolean not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_attachment_analysis primary key (id),
    constraint fk_attachment_analysis_attachment foreign key (attachment_id) references complaint_attachments (id),
    constraint uk_attachment_analysis_attachment unique (attachment_id)
);

create index idx_processing_jobs_status_created_at on processing_jobs (status, created_at);
create index idx_evidence_snapshots_complaint on evidence_snapshots (complaint_id);
create index idx_human_reviews_complaint on human_reviews (complaint_id, created_at);
create index idx_legal_document_versions_effective on legal_document_versions (jurisdiction_code, status, effective_from, effective_to);
