package egovframework.example.complaint.domain;

public enum KnowledgePurpose {
	OFFICIAL_LAW,
	PROCEDURE,
	HISTORICAL_CASE,
	STYLE,
	UNVERIFIED_LEGACY,
	LOCAL_ORDINANCE_REFERENCE,
	STYLE_REFERENCE,
	ORGANIZATION_ROUTING,
	EVALUATION_TRAINING
}
